# Part 1: merging data sets

This Notebook contains:
1. Import libraries and data
2. Merge data
3. Export data *italicized text*

### 01. Import necessary libraries and data from Google Drive

In [ ]:
# Import libraries

import pandas as pd
import os

In [ ]:
# Connect cloud to my GDRIVE

from google.colab import drive
drive.mount('/content/gdrive')
!ls # will show you can now access the gdrive locally

Mounted at /content/gdrive
drive  gdrive  sample_data

In [ ]:
# Set file path

path = "/content/gdrive/MyDrive/Colab Notebooks"

In [ ]:
# Import the customer data set

df1 = pd.read_csv(os.path.join(path,'df_small.csv'))

In [ ]:
# Check the data set (shape, columns, head)

print(df1.columns)

Index(['Unnamed: 0', 'user_id', 'first_name', 'last_name', 'gender', 'state',
       'age', 'date_joined', 'number_of_dependents', 'marital_status',
       'income'],
      dtype='object')

In [ ]:
df1.head()

,Unnamed: 0,user_id,first_name,last_name,gender,state,age,date_joined,number_of_dependents,marital_status,income
0,0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [ ]:
print(df1.shape)

(206209, 11)

In [ ]:
# Import the second data set of aggregated orders & products

df2 = pd.read_pickle(os.path.join(path, 'df_large.pkl'))

In [ ]:
# Check the imported dataframe (shape, columns, head)

print(df2.shape)

(32404859, 22)

In [ ]:
print(df2.columns)

Index(['order_id', 'user_id', 'order_number', 'orders_day_of_week',
       'order_hour_of_day', 'days_since_last_order', 'product_id',
       'add_to_cart_order', 'reordered', 'product_name', 'aisle_id',
       'department_id', 'prices', 'price_range_loc', 'busiest_days',
       'busiest_hours', 'max_order', 'loyalty_flag', 'avg_price',
       'spending_flag', 'median_dslo', 'frequency_flag'],
      dtype='object')

In [ ]:
df2.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,prices,price_range_loc,busiest_days,busiest_hours,max_order,loyalty_flag,avg_price,spending_flag,median_dslo,frequency_flag
0,2539329,1,1,2,8,0,196,1,0,Soda,...,0.0,Mid-range product,Regularly busy,Average orders,10,New customer,6.367796,Low spender,20.5,Non-frequent customer
1,2398795,1,2,3,7,15,196,1,1,Soda,...,1.0,Mid-range product,Slowest days,Average orders,10,New customer,6.367796,Low spender,20.5,Non-frequent customer
2,473747,1,3,3,12,21,196,1,1,Soda,...,1.0,Mid-range product,Slowest days,Most orders,10,New customer,6.367796,Low spender,20.5,Non-frequent customer
3,2254736,1,4,4,7,29,196,1,1,Soda,...,1.0,Mid-range product,Slowest days,Average orders,10,New customer,6.367796,Low spender,20.5,Non-frequent customer
4,431534,1,5,4,15,28,196,1,1,Soda,...,1.0,Mid-range product,Slowest days,Most orders,10,New customer,6.367796,Low spender,20.5,Non-frequent customer

## 02. Merge the two date sets

In [ ]:
# Attemp a merge

df3 = df2.merge(df1, on = ['user_id'], indicator = True)

In [ ]:
# Confirm merge output through merge flag frequency

df3['_merge'].value_counts(dropna = False) # result only in both, we know it´s a full-match independently.

both          32404859
left_only            0
right_only           0
Name: _merge, dtype: int64

In [ ]:
# Check output for new combined data set (shape, columns, head)

print(df3.shape)

(32404859, 33)

In [ ]:
print(df3.columns)

Index(['order_id', 'user_id', 'order_number', 'orders_day_of_week',
       'order_hour_of_day', 'days_since_last_order', 'product_id',
       'add_to_cart_order', 'reordered', 'product_name', 'aisle_id',
       'department_id', 'prices', 'price_range_loc', 'busiest_days',
       'busiest_hours', 'max_order', 'loyalty_flag', 'avg_price',
       'spending_flag', 'median_dslo', 'frequency_flag', 'Unnamed: 0',
       'first_name', 'last_name', 'gender', 'state', 'age', 'date_joined',
       'number_of_dependents', 'marital_status', 'income', '_merge'],
      dtype='object')

In [ ]:
df3.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,first_name,last_name,gender,state,age,date_joined,number_of_dependents,marital_status,income,_merge
0,2539329,1,1,2,8,0,196,1,0,Soda,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
1,2398795,1,2,3,7,15,196,1,1,Soda,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
2,473747,1,3,3,12,21,196,1,1,Soda,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
3,2254736,1,4,4,7,29,196,1,1,Soda,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
4,431534,1,5,4,15,28,196,1,1,Soda,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both

In [ ]:
# Drop unneccesary columns

df_final = df3.drop(columns = ['_merge','Unnamed: 0'])

In [ ]:
# Check output

print(df_final.shape)  # two columns dropped as intended

(32404859, 31)

## 03. Export data

In [ ]:
# Export new dataframe as pickle file and save into my GDRIVE

df_final.to_pickle(os.path.join(path, 'final_merge.pkl'))